LibraryManagement/LibraryManagement/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryManagement.Models;
using LibraryManagement.Models.Context;
using Microsoft.AspNetCore.Authorization;

namespace LibraryManagement.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryDbContext _LibraryDbContext;

        public BooksController(LibraryDbContext libraryDbContext)
        {
            _LibraryDbContext = libraryDbContext;
        }

        [Authorize]

        public IActionResult BookDetail(int id)
        {
            var book = _LibraryDbContext.Books
                .Include(b => b.Author)
                .Include(b => b.Category)
                .FirstOrDefault(b => b.BookId == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        public IActionResult List(string category)
        {
            List<Books> books = _LibraryDbContext.Books
                .Include(b => b.Author)
                .Include(b => b.Category)
                .Where(b => b.Category != null && b.Category.Name.ToLower() == category.ToLower())
                .OrderBy(b => b.BookId)
                .ToList();

            ViewBag.Books = books;
            ViewBag.Category = category;
            return View();
        }

        [Authorize]

        public IActionResult ReadPdf(int id)
        {
            var book = _LibraryDbContext.Books.FirstOrDefault(b => b.BookId == id);
            if (book == null || string.IsNullOrEmpty(book.Pdf))
            {
                return NotFound("This book has not have the PDF version.");
            }

            var pdfUrl = Url.Content($"/{book.Pdf}");
            ViewBag.PdfPath = pdfUrl;
            return View();
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var libraryDbContext = _LibraryDbContext.Books.Include(b => b.Author).Include(b => b.Category);
            return View(await libraryDbContext.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = await _LibraryDbContext.Books
                .Include(b => b.Author)
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_LibraryDbContext.Authors, "AuthorId", "FirstName");
            ViewData["CategoryId"] = new SelectList(_LibraryDbContext.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookId,Title,Description,BookCode,Publisher,PublishedYear,CategoryId,AuthorId,TotalCopies,AvailableCopies,CreatedDate,Avatar,Pdf")] Books books)
        {
            if (ModelState.IsValid)
            {
                _LibraryDbContext.Add(books);
                await _LibraryDbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_LibraryDbContext.Authors, "AuthorId", "FirstName", books.AuthorId);
            ViewData["CategoryId"] = new SelectList(_LibraryDbContext.Categories, "CategoryId", "Name", books.CategoryId);
            return View(books);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = await _LibraryDbContext.Books.FindAsync(id);
            if (books == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_LibraryDbContext.Authors, "AuthorId", "FirstName", books.AuthorId);
            ViewData["CategoryId"] = new SelectList(_LibraryDbContext.Categories, "CategoryId", "Name", books.CategoryId);
            return View(books);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookId,Title,Description,BookCode,Publisher,PublishedYear,CategoryId,AuthorId,TotalCopies,AvailableCopies,CreatedDate,Avatar,Pdf")] Books books)
        {
            if (id != books.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _LibraryDbContext.Update(books);
                    await _LibraryDbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BooksExists(books.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_LibraryDbContext.Authors, "AuthorId", "FirstName", books.AuthorId);
            ViewData["CategoryId"] = new SelectList(_LibraryDbContext.Categories, "CategoryId", "Name", books.CategoryId);
            return View(books);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = await _LibraryDbContext.Books
                .Include(b => b.Author)
                .Include(b => b.Category)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var books = await _LibraryDbContext.Books.FindAsync(id);
            if (books != null)
            {
                _LibraryDbContext.Books.Remove(books);
            }

            await _LibraryDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BooksExists(int id)
        {
            return _LibraryDbContext.Books.Any(e => e.BookId == id);
        }
    }
}

LibraryManagement/LibraryManagement/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryManagement.Models;
using LibraryManagement.Models.Context;

namespace LibraryManagement.Controllers
{
    public class LoansController : Controller
    {
        private readonly LibraryDbContext _context;

        public LoansController(LibraryDbContext context)
        {
            _context = context;
        }

        // GET: Loans
        public async Task<IActionResult> Index()
        {
            var libraryDbContext = _context.Loans.Include(l => l.Book).Include(l => l.User);
            return View(await libraryDbContext.ToListAsync());
        }

        // GET: Loans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loans = await _context.Loans
                .Include(l => l.Book)
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.LoanId == id);
            if (loans == null)
            {
                return NotFound();
            }

            return View(loans);
        }

        // GET: Loans/Create
        public IActionResult Create()
        {
            ViewData["BookId"] = new SelectList(_context.Books, "BookId", "Title");
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email");
            return View();
        }

        // POST: Loans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LoanId,UserId,BookId,LoanDate,DueDate,ReturnDate,Status")] Loans loans)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loans);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "BookId", "Title", loans.BookId);
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", loans.UserId);
            return View(loans);
        }

        // GET: Loans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loans = await _context.Loans.FindAsync(id);
            if (loans == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Books, "BookId", "Title", loans.BookId);
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", loans.UserId);
            return View(loans);
        }

        // POST: Loans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LoanId,UserId,BookId,LoanDate,DueDate,ReturnDate,Status")] Loans loans)
        {
            if (id != loans.LoanId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loans);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoansExists(loans.LoanId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "BookId", "Title", loans.BookId);
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "Email", loans.UserId);
            return View(loans);
        }

        // GET: Loans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loans = await _context.Loans
                .Include(l => l.Book)
                .Include(l => l.User)
                .FirstOrDefaultAsync(m => m.LoanId == id);
            if (loans == null)
            {
                return NotFound();
            }

            return View(loans);
        }

        // POST: Loans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var loans = await _context.Loans.FindAsync(id);
            if (loans != null)
            {
                _context.Loans.Remove(loans);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoansExists(int id)
        {
            return _context.Loans.Any(e => e.LoanId == id);
        }
    }
}

LibraryManagement/LibraryManagement/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryManagement.Models;
using LibraryManagement.Models.Context;

namespace LibraryManagement.Controllers
{
    public class UserController : Controller
    {
        private readonly LibraryDbContext _context;

        public UserController(LibraryDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Fullname,Description,Password,Email,Phone,Address,Status,CreatedDate,UserCode,IsLocked,IsDeleted,IsActive,ActiveCode,Avatar")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Fullname,Description,Password,Email,Phone,Address,Status,CreatedDate,UserCode,IsLocked,IsDeleted,IsActive,ActiveCode,Avatar")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.UserId == id);
        }
    }
}

LibraryManagement/LibraryManagement/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <style>
        /* Header styling */

        header h2 {
            font-size: 1.75rem;
            font-weight: bold;
            margin: 0;
        }

        /* Sidebar styling */
        nav {
            background-color: #9fb6c3;
            color: black;
            position: fixed;
            top: 0;
            left: 0;
            width: 250px;
            height: 100vh;
        }

            nav h5 {
                font-weight: bold;
                font-size: 1.25rem;
                color: black;
                margin-bottom: 1rem;
            }

        .nav-link {
            color: black;
            font-weight: 500;
            padding: 0.5rem 1rem;
            transition: color 0.2s, background-color 0.2s;
            border-radius: 0.25rem;
        }

            .nav-link:hover, .nav-link.active {
                background-color: var(--dark-skyblue);
                color: #ffffff;
            }

        /* Content area styling */
        main {
            margin-left: 200px;
            display: flex;
            flex-grow: 1;
        }

        .container-fluid {
            gap: 20px;
        }

        body {
            background-color: #f8f8f9;
        }
    </style>
</head>
<body>

    <!-- Header -->
    <header class="d-flex justify-content-center align-items-center py-2">
        <h2>Library Management System - Admin Panel</h2>
        <div class="d-flex justify-content-between">
            <a asp-controller="Home" asp-action="Index" class="btn btn-info mx-1 d-flex align-items-center">
                Back To HomePage
            </a>
            <a asp-controller="Account" asp-action="Logout" class="btn btn-info mx-1 d-flex align-items-center">
                <i class="fas fa-sign-out-alt"></i> Logout
            </a>
        </div>
    </header>

    <div class="container-fluid flex-grow-1 d-flex">
        <!-- Sidebar / Menu -->
        <nav class="p-3" style="width: 200px;">
            <h5>Menu</h5>
            <ul class="nav flex-column">
                <a class="nav-link" asp-controller="Admin" asp-action="Dashboard"><i class="fas fa-chalkboard"></i> Dashboard</a>
                <a class="nav-link" asp-controller="Books" asp-action="Index"><i class="fas fa-book"></i> Books</a>
                <a class="nav-link" asp-controller="Authors" asp-action="Index"><i class="fas fa-user"></i> Authors</a>
                <a class="nav-link" asp-controller="Loans" asp-action="Index"><i class="fas fa-money-check-alt"></i> Loans</a>
                <a class="nav-link" asp-controller="Categories" asp-action="Index"><i class="fas fa-list"></i> Category</a>
                <a class="nav-link" asp-controller="User" asp-action="Index"><i class="fas fa-users"></i> User</a>
            </ul>
        </nav>

        <!-- Content Area -->
    </div>
    <main>
        @RenderBody()
    </main>

</body>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</html>

LibraryManagement/LibraryManagement/Views/Shared/_Carousel.cshtml
@model IEnumerable<LibraryManagement.Models.Carousel>

<div id="carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        @foreach (var item in Model)
        {
            <div class="carousel-item @(item == Model.First() ? "active" : "")">
                <img src="@item.ImageUrl" class="d-block w-100 h-50" alt="@item.Title">
                <div class="carousel-caption d-none d-md-block">
                    <h5>@item.Title</h5>
                    <p>@item.Description</p>
                </div>
            </div>
        }
    </div>
    <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

LibraryManagement/LibraryManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="~/LibraryManagement.styles.css" asp-append-version="true" />
</head>
<body>
    @if (ViewData["IsAdminLayout"] != null && (bool)ViewData["IsAdminLayout"])
    {
        @RenderBody()
    }
    else
    {
        <header class="d-flex bg-light justify-content-between align-items-center" style="padding: 20px">
            <a asp-controller="Home" asp-action="Index">
                <img src="~/images/logo-4.png" alt="Logo" width="100" />
            </a>

            <div class="search-box" style="width: 50%">
                <form method="get" asp-action="Search">
                    <div class="input-group">
                        <input type="text" name="search" placeholder="Search books..." class="form-control" />
                        <span class="input-group-text">
                            <i class="fas fa-search"></i>
                        </span>
                    </div>
                </form>
            </div>
            <div class="d-flex align-items-center">
                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-controller="Account" asp-action="Logout" class="btn btn-outline-danger d-flex align-items-center">
                        <i class="fas fa-sign-out-alt me-2"></i> Logout
                    </a>
                }
                else
                {
                    <a asp-controller="Account" asp-action="SignUp" class="btn btn-outline-success d-flex align-items-center me-2">
                        <i class="fas fa-user-plus me-2"></i> Sign Up
                    </a>
                    <a asp-controller="Account" asp-action="Login" class="btn btn-primary d-flex align-items-center">
                        <i class="fas fa-sign-in-alt me-2"></i> Login
                    </a>
                }
            </div>
        </header>

        <div class="nav-body">
            <div class="dropdown">
                <button type="button" class="btn dropdown-toggle text-black" data-bs-toggle="dropdown" id="dropdownMenuButton">
                    Book List
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <li><a class="dropdown-item" href="#">Link 1</a></li>
                    <li><a class="dropdown-item" href="#">Link 2</a></li>
                    <li><a class="dropdown-item" href="#">Link 3</a></li>
                </ul>
            </div>

            <nav>
                <ul class="navbar-menu">
                    <li><a asp-controller="Home" asp-action="Index" class="text-decoration-none text-black">Home page</a></li>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li><a asp-controller="Admin" asp-action="Dashboard" class="text-decoration-none text-black"> Administration</a></li>
                    }
                    <li>
                        <a asp-controller="Books" asp-action="List" asp-route-category="Programming" class="text-decoration-none text-black">Programming Book</a>
                    </li>
                    <li>
                        <a asp-controller="Books" asp-action="List" asp-route-category="Fiction" class="text-decoration-none text-black">Fiction Book</a>
                    </li>
                    <li>
                        <a asp-controller="Books" asp-action="List" asp-route-category="Science Fiction" class="text-decoration-none text-black">Science Fiction Book</a>
                    </li>
                </ul>
            </nav>
        </div>


        <main role="main" class="pb-3">
            @RenderBody()
        </main>

        <footer class="py-4 bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h5>About Us</h5>
                        <p>Library Management System provides comprehensive solutions for managing library resources and services.</p>
                    </div>
                    <div class="col-md-4">
                        <h5>Contact</h5>
                        <p>
                            Email: library@example.com<br>
                            Phone: (123) 456-7890<br>
                            Address: 123 Library Street
                        </p>
                    </div>
                    <div class="col-md-4">
                        <h5>Quick Links</h5>
                        <ul>
                            <li><a href="#" class="text-muted">Home</a></li>
                            <li><a href="#" class="text-muted">Books</a></li>
                            <li><a href="#" class="text-muted">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <hr>
                <p class="text-center mb-0">&copy; 2024 - Library Management System - All rights reserved</p>
            </div>
        </footer>
    }


</body>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)

</html>